export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TRANSFER_PARSE_ERROR: "TRANSFER_PARSE_ERROR",
  TRANSFER_VERSION_MISMATCH: "TRANSFER_VERSION_MISMATCH",
  TRANSFER_REFERENCE_MISSING: "TRANSFER_REFERENCE_MISSING",
  TRANSFER_DMX_CONFLICT: "TRANSFER_DMX_CONFLICT"
} as const;
