export const TRANSFER_ERROR_CODES = {
  TRANSFER_UNSUPPORTED_VERSION: "TRANSFER_UNSUPPORTED_VERSION",
  TRANSFER_MALFORMED_PAYLOAD: "TRANSFER_MALFORMED_PAYLOAD",
  TRANSFER_MISSING_FIXTURE: "TRANSFER_MISSING_FIXTURE",
  TRANSFER_MISSING_SCENE: "TRANSFER_MISSING_SCENE",
  TRANSFER_DMX_CONFLICT: "TRANSFER_DMX_CONFLICT",
  TRANSFER_PERSIST_FAILED: "TRANSFER_PERSIST_FAILED"
} as const;

export type TransferErrorCode = (typeof TRANSFER_ERROR_CODES)[keyof typeof TRANSFER_ERROR_CODES];
